import { useEffect, useMemo, useState } from "react";
import { apiCall } from "../api/client";
import RiskRadar from "./RiskRadar";
import { Empty, Form, Loader, PageHeader, Section, StatsRow, Table } from "./DashboardComponents";
import "./Product.css";

const nav = [
  ["Fleet", "vessels", "FLEET"], ["Add vessel", "addVessel", "FLEET"],
  ["Commanders", "captains", "CREW"], ["Register captain", "addCaptain", "CREW"], ["Assign command", "assignCaptain", "CREW"],
  ["Logbook", "logs", "COMPLIANCE"], ["Add entry", "addLog", "COMPLIANCE"], ["Watchlist", "violations", "COMPLIANCE"],
  ["Access control", "users", "ADMIN"],
];

export default function Dashboard({ user, onLogout }) {
  const [activeTab, setActiveTab] = useState("vessels"), [vessels, setVessels] = useState([]), [logs, setLogs] = useState([]), [captains, setCaptains] = useState([]);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [search, setSearch] = useState(""), [passport, setPassport] = useState(null);
  const [vesselForm, setVesselForm] = useState({ name: "", imo_number: "", flag_state: "", type: "" }), [captainForm, setCaptainForm] = useState({ name: "", license_number: "", nationality: "" }), [logForm, setLogForm] = useState({ vessel_id: "", sulfur_level: "", waste_amount: "" }), [assignForm, setAssignForm] = useState({ captain_id: "", vessel_id: "", start_date: "" });
  const [message, setMessage] = useState(""), [users, setUsers] = useState([]), [usersLoading, setUsersLoading] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const [v, l, c] = await Promise.all([apiCall("/api/v1/vessels"), apiCall("/api/v1/logs"), apiCall("/api/v1/captains")]); setVessels(Array.isArray(v) ? v : []); setLogs(Array.isArray(l) ? l : []); setCaptains(Array.isArray(c) ? c : []); } catch (e) { setError(e.message || "We couldn't reach the fleet records."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const violations = logs.filter(l => l.violation);
  const fleetRisk = useMemo(() => vessels.map(v => { const own = logs.filter(l => l.vessel_id === v.id), max = own.reduce((m, l) => Math.max(m, Number(l.sulfur_level) || 0), 0), issues = own.filter(l => l.violation).length; return { ...v, logCount: own.length, violations: issues, score: Math.min(100, issues * 35 + Math.max(0, max - .5) * 50) }; }).sort((a, b) => b.score - a.score), [vessels, logs]);
  const submit = async (endpoint, body, reset, success) => { try { const r = await apiCall(endpoint, "POST", body); if (r.id || r.message) { setMessage(`✓ ${success}`); reset(); load(); } else setMessage(r.message || "Something needs your attention."); } catch (e) { setMessage(e.message || "Something needs your attention."); } };
  const exportCsv = () => { const rows = [["Vessel", "IMO", "Logs", "Violations", "Risk score"], ...fleetRisk.map(v => [v.name, v.imo_number, v.logCount, v.violations, v.score.toFixed(0)])]; const url = URL.createObjectURL(new Blob([rows.map(r => r.join(",")).join("\n")], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = "fleet-watchlist.csv"; a.click(); URL.revokeObjectURL(url); };
  const visible = fleetRisk.filter(v => `${v.name} ${v.imo_number} ${v.flag_state} ${v.type}`.toLowerCase().includes(search.toLowerCase()));
  const groups = ["FLEET", "CREW", "COMPLIANCE"];
  const canManageFleet = user?.role === "admin";
  const canAddLog = ["admin", "officer"].includes(user?.role);
  const visibleNav = nav;
  const loadUsers = async () => { setUsersLoading(true); setMessage(""); try { setUsers(await apiCall("/api/v1/users")); } catch (e) { setMessage(e.message || "We couldn't load access records."); } finally { setUsersLoading(false); } };
  const changeTab = id => {
    const adminOnly = ["addVessel", "addCaptain", "assignCaptain", "users"];
    if (adminOnly.includes(id) && !canManageFleet) { setMessage("Administrator access is required for this action."); return; }
    if (id === "addLog" && !canAddLog) { setMessage("Officer or administrator access is required to add a log entry."); return; }
    setActiveTab(id);
    setMessage("");
    if (id === "users") loadUsers();
  };
  const changeRole = async (id, role) => { try { const updated = await apiCall(`/api/v1/users/${id}/role`, "PATCH", { role }); setUsers(current => current.map(member => member.id === id ? { ...member, role: updated.role } : member)); setMessage(updated.message); } catch (e) { setMessage(e.message || "We couldn't update that access level."); } };
  const openPassport = async vesselId => { setPassport("loading"); try { setPassport(await apiCall(`/api/v1/vessels/${vesselId}/passport`)); } catch (e) { setPassport(null); setError(e.message || "We couldn't open this vessel passport."); } };
  let content;
  if (loading) content = <Loader />;
  else if (activeTab === "vessels") content = <><StatsRow vessels={vessels} logs={logs} violations={violations} captains={captains} /><div className="fleet-tools"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Find a vessel, IMO, flag or type" /><button className="quiet-button" onClick={exportCsv}>Export watchlist</button></div>{vessels.length ? <><Table headers={["Vessel", "IMO number", "Flag state", "Class", "Risk"]} rows={visible.map(v => [<button className="vessel-link" onClick={() => openPassport(v.id)} key="vessel">{v.name}<small>View passport →</small></button>, v.imo_number, v.flag_state || "—", v.type || "—", <span className={`risk-pill ${v.score >= 70 ? "risk-high" : ""}`} key="risk">{v.score.toFixed(0)} / 100</span>])} /><RiskRadar fleetRisk={fleetRisk} /></> : <Empty message="Register the first vessel in your fleet." action="Add a vessel" onAction={() => changeTab("addVessel")} />}</>;
  else if (activeTab === "captains") content = captains.length ? <Table headers={["Commander", "License", "Nationality"]} rows={captains.map(c => [c.name, c.license_number || "—", c.nationality || "—"])} /> : <Empty message="Your fleet is ready for its first commander." action="Register a captain" onAction={() => changeTab("addCaptain")} />;
  else if (activeTab === "logs") content = logs.length ? <Table headers={["Vessel", "Sulfur level", "Waste", "Status", "Recorded"]} rows={logs.map(l => [vessels.find(v => v.id === l.vessel_id)?.name || "Unknown vessel", `${l.sulfur_level}%`, `${l.waste_amount} t`, l.violation ? <span className="risk-pill risk-high" key="status">Needs care</span> : <span className="risk-pill" key="status">In order</span>, new Date(l.created_at || l.timestamp).toLocaleDateString()])} /> : <Empty message="A well-kept logbook begins with one entry." action="Add a log entry" onAction={() => changeTab("addLog")} />;
  else if (activeTab === "violations") content = violations.length ? <Section title="Items to resolve"><Table headers={["Vessel", "Sulfur level", "Waste", "Recorded"]} rows={violations.map(l => [vessels.find(v => v.id === l.vessel_id)?.name || "Unknown vessel", `${l.sulfur_level}%`, `${l.waste_amount} t`, new Date(l.created_at || l.timestamp).toLocaleDateString()])} /></Section> : <Empty message="Everything in the current log meets your standard." action="Return to fleet" onAction={() => changeTab("vessels")} />;
  else if (activeTab === "addVessel") content = <Form fields={[{ label: "Vessel name", key: "name", placeholder: "MV Aurora" }, { label: "IMO number", key: "imo_number", placeholder: "IMO 9876543" }, { label: "Flag state", key: "flag_state", placeholder: "India" }, { label: "Vessel type", key: "type", placeholder: "Cargo carrier" }]} values={vesselForm} onChange={(k, v) => setVesselForm({ ...vesselForm, [k]: v })} onSubmit={() => vesselForm.name && vesselForm.imo_number ? submit("/api/v1/vessels", vesselForm, () => setVesselForm({ name: "", imo_number: "", flag_state: "", type: "" }), "Vessel added to your fleet.") : setMessage("Vessel name and IMO number are required.")} message={message} submitLabel="Register vessel" />;
  else if (activeTab === "addCaptain") content = <Form fields={[{ label: "Full name", key: "name", placeholder: "Capt. Arjun Rao" }, { label: "License number", key: "license_number", placeholder: "LIC-001" }, { label: "Nationality", key: "nationality", placeholder: "Indian" }]} values={captainForm} onChange={(k, v) => setCaptainForm({ ...captainForm, [k]: v })} onSubmit={() => captainForm.name ? submit("/api/v1/captains", captainForm, () => setCaptainForm({ name: "", license_number: "", nationality: "" }), "Commander registered.") : setMessage("A commander's name is required.")} message={message} submitLabel="Register commander" />;
  else if (activeTab === "addLog") content = <Form fields={[{ label: "Vessel", key: "vessel_id", type: "select", options: vessels.map(v => ({ value: v.id, label: v.name })) }, { label: "Sulfur level (%)", key: "sulfur_level", type: "number", placeholder: "0.50" }, { label: "Waste amount (tonnes)", key: "waste_amount", type: "number", placeholder: "0.00" }]} values={logForm} onChange={(k, v) => setLogForm({ ...logForm, [k]: v })} onSubmit={() => logForm.vessel_id && logForm.sulfur_level && logForm.waste_amount ? submit("/api/v1/logs", { ...logForm, vessel_id: +logForm.vessel_id, sulfur_level: +logForm.sulfur_level, waste_amount: +logForm.waste_amount }, () => setLogForm({ vessel_id: "", sulfur_level: "", waste_amount: "" }), "Log entry recorded.") : setMessage("Every field helps tell the full story.")} message={message} submitLabel="Record entry" />;
  else if (activeTab === "users") content = <Section title="Team access"><p className="access-intro">Only administrators can set roles. Changes take effect when the member next signs in.</p>{usersLoading ? <Loader /> : <Table headers={["Member", "Email", "Access level", ""]} rows={users.map(member => [member.name, member.email, <select className="role-select" value={member.role} onChange={e => changeRole(member.id, e.target.value)} disabled={member.id === user?.id} key="role"><option value="viewer">Viewer</option><option value="officer">Officer</option><option value="admin">Administrator</option></select>, member.id === user?.id ? <small key="you">Your account</small> : ""])} />}{message && <p className={`form-message ${message.startsWith("Access") ? "success" : "error"}`}>{message}</p>}</Section>;
  else content = <Form fields={[{ label: "Commander", key: "captain_id", type: "select", options: captains.map(c => ({ value: c.id, label: c.name })) }, { label: "Vessel", key: "vessel_id", type: "select", options: vessels.map(v => ({ value: v.id, label: v.name })) }, { label: "Start date", key: "start_date", type: "date" }]} values={assignForm} onChange={(k, v) => setAssignForm({ ...assignForm, [k]: v })} onSubmit={() => assignForm.captain_id && assignForm.vessel_id && assignForm.start_date ? submit("/api/v1/assignments", { ...assignForm, captain_id: +assignForm.captain_id, vessel_id: +assignForm.vessel_id }, () => setAssignForm({ captain_id: "", vessel_id: "", start_date: "" }), "Command assigned.") : setMessage("Choose a commander, a vessel, and a start date.")} message={message} submitLabel="Assign command" />;
  if (passport) return <PassportView passport={passport} onBack={() => setPassport(null)} />;
  return <div className="product-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">✦</span><div><small>Maritime</small><strong>Dominion</strong></div></div><div className="identity"><span>ON WATCH · {user?.role || "unauthenticated"}</span><b>{user?.name || "Commander"}</b><small>{user?.email}</small></div><nav>{[...groups, "ADMIN"].map(group => <div className="nav-group" key={group}><span>{group}</span>{visibleNav.filter(n => n[2] === group).map(([label, id]) => <button className={activeTab === id ? "active" : ""} onClick={() => changeTab(id)} key={id}>{label}{id === "violations" && violations.length > 0 && <b>{violations.length}</b>}</button>)}</div>)}</nav><button className="sign-out" onClick={onLogout}>Sign out <span>↗</span></button></aside><main><div className="topline"><span>Monday, 13 July</span><span>Calm waters. Clear records.</span></div><PageHeader activeTab={activeTab} />{error && <div className="notice">{error}<button onClick={load}>Try again</button></div>}{message && !["addVessel", "addCaptain", "assignCaptain", "addLog", "users"].includes(activeTab) && <div className="notice">{message}</div>}{content}</main></div>;
}

function PassportView({ passport, onBack }) {
  if (passport === "loading") return <div className="product-shell passport-loading"><Loader /></div>;
  const { vessel, captains = [], logs = [] } = passport;
  const commander = captains.find(c => !c.end_date);
  const highestSulfur = Math.max(0, ...logs.map(l => Number(l.sulfur_level) || 0));
  const violations = logs.filter(l => l.violation).length;
  const clear = highestSulfur <= .5 && violations === 0 && commander;
  return <div className="passport-page"><button className="back-button" onClick={onBack}>← Return to fleet</button><div className="passport-hero"><div><p className="eyebrow">VESSEL PASSPORT</p><h1>{vessel.name}</h1><p className="passport-imo">{vessel.imo_number}</p></div><div className={`entry-stamp ${clear ? "approved" : "review"}`}><span>PORT ENTRY</span><b>{clear ? "CLEARED" : "REVIEW"}</b><small>Live operational record</small></div></div><div className="passport-grid"><Section title="Vessel identity"><div className="passport-facts"><span>Flag state<b>{vessel.flag_state || "Not recorded"}</b></span><span>Vessel class<b>{vessel.type || "Not recorded"}</b></span><span>Current commander<b>{commander?.name || "Awaiting assignment"}</b></span><span>Log entries<b>{logs.length}</b></span></div></Section><Section title="Compliance watch"><div className="check-row"><span>Sulfur threshold <small>IMO maximum 0.5%</small></span><b className={highestSulfur <= .5 ? "pass" : "fail"}>{highestSulfur <= .5 ? "In order" : "Above threshold"}</b></div><div className="check-row"><span>Recorded violations <small>Across this vessel record</small></span><b className={violations ? "fail" : "pass"}>{violations || "None"}</b></div><div className="check-row"><span>Command status <small>Assigned master required</small></span><b className={commander ? "pass" : "fail"}>{commander ? "In command" : "Unassigned"}</b></div></Section><Section title="Passage log">{logs.length ? <Table headers={["Sulfur", "Waste", "Status", "Date"]} rows={logs.map(l => [`${l.sulfur_level}%`, `${l.waste_amount} t`, <span className={`risk-pill ${l.violation ? "risk-high" : ""}`} key="s">{l.violation ? "Attention" : "Clear"}</span>, new Date(l.timestamp || l.created_at).toLocaleDateString()])} /> : <p className="no-record">No log entries have been recorded for this vessel.</p>}</Section></div></div>;
}
