import "./MarketingPage.css";

const content = {
  features: { mark: "The instruments", title: "Command is a craft.", lead: "A considered fleet workspace for the people who carry responsibility across open water.", blocks: [["Fleet clarity", "Every vessel, log, captain and exception in one quietly ordered view."], ["Compliance pulse", "Turn routine reporting into an early, intelligible signal."], ["Vessel passports", "A living record of identity, command and operational standards."]], quote: "Less noise. More command." },
  about: { mark: "Our bearing", title: "Built for those who answer to the horizon.", lead: "Maritime Dominion brings the discipline of a ship's log to a modern operating system—precise, human, and made for pride in the work.", blocks: [["Grounded", "We honour the details that keep people, cargo, and coastlines safe."], ["Exacting", "Every interface earns its place; every record remains useful."], ["Enduring", "A calm, reliable companion for the work that happens beyond shore."]], quote: "The sea asks for clarity." },
  contact: { mark: "Open a channel", title: "Start a more confident watch.", lead: "Whether you are modernising one vessel or bringing a whole operation into focus, the conversation begins here.", blocks: [["For operators", "Build a more complete picture of your fleet."], ["For captains", "Make every handover and record feel deliberate."], ["For partners", "Talk to us about a considered operational future."]], quote: "The first signal is a simple one." },
};

export default function MarketingPage({ page, onBack, onGetStarted }) {
  const item = content[page] || content.features;
  return <div className="marketing-page"><header className="marketing-nav"><button onClick={onBack} className="wordmark"><i>✦</i> Maritime Dominion</button><div><button onClick={() => onBack()}>Home</button><button className="nav-cta" onClick={onGetStarted}>Enter command</button></div></header><main><div className="marketing-intro"><p>{item.mark}</p><h1>{item.title}</h1><div className="intro-rule" /><h2>{item.lead}</h2></div><section className="marketing-blocks">{item.blocks.map(([title, body], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</section><section className="marketing-quote"><p>“{item.quote}”</p><span>MARITIME DOMINION · EST. 2026</span></section>{page === "contact" && <section className="contact-card"><p>WRITE TO US</p><a href="mailto:hello@maritimedominion.com">hello@maritimedominion.com</a><span>We’ll meet you at the right latitude.</span></section>}<button className="marketing-button" onClick={onGetStarted}>Begin with your fleet <b>→</b></button></main></div>;
}
